### ISSUE TITLE
Controller level 4 issue with get range to

### ISSUE THREAD

**Issue by bboyman31** [Jargon64/Screeps#2]
I've been testing out your code to see if I can find a basis for my new code, and it seems when the phase is at 4 the error "a.getRangeTo is not a function" spams the console. No line errors or anything just can't seem to find the cause of this issue

**Comment by Jargon64** [comment]
Had no idea anyone was using my code :) 

The phased build order is something I've thrown together this evening to prevent an overwhelming attempt to build everything at the same time and also before it's possible, so it's no surprise there's issues. Haven't given it a proper run through the simulator yet. 

However, that being said, phase 4 builds the roads to the sources using a path finding algorithm and it's done so in an anonymous function (meaning no line numbers), so my bet is that is where the issue lies. 

I will investigate tomorrow when I have time.

**Comment by bboyman31** [comment]
Yeah, sorry about the surprise, other than that this is very well thought out code and honestly, much more readable than many other things I've have looked over in the past. I've been running it at 500% speed in the simulator for about 8 hours now. So it just got to phase 4 and I noticed the issue, I will try to work out what is causing it as well.

Thanks!

**Comment by Jargon64** [comment]
Running it through the simulator now. Only reason it I haven't done it until now is because it gets nowhere with the standard simulator that spawns hostile creeps. So running it an empty room with 3 sources. I did spot a whoopsie quite early on. Some creeps just hung around the spawn and didn't do anything, but I've fixed that now. Rapidly approaching controller level 3 so we'll see.

Also, I noticed that there is a long lull before controller level 3 is achieve where the creeps don't do much, so will probably reorder the phasing a bit and get the roads down after the first 5 extensions are built. Will speed up harvesting too.

**Comment by bboyman31** [comment]
Yeah, I noticed that as well. I've been trying to find the cause of the a.getRangeTo bug but I couldn't really pinpoint it

**Comment by Jargon64** [comment]
Figured out the issue. When you store a game object in memory then refer to it later, it deserialises it. Which is fine, except it has none of the methods on the object anymore, just the properties. The object in question was:

`room.memory.home`

Which was being used as the origin point for the path finding. I just changed it to:

`let home = Game.getObjectById(room.memory.home.id)`

And used that instead.
